### ISSUE TITLE
Push Github Actions results to Slack

### ISSUE THREAD

**Issue by oubiwann** [oxur/component#18]
See the setup used by hexagram30/raster:
* https://github.com/hexagram30/raster/blob/master/.github/workflows/go.yml
* https://github.com/hexagram30/raster/settings/installations
* https://github.com/organizations/hexagram30/settings/installations/5973762
* https://github.com/hexagram30/raster/settings/secrets

Steps:
* [x] Copy job from the raster example to the rust.yml component Github Actions file
* [x] Install Slack on oxur Github org
* [x] Install actions: 
   * [x] Check that this is the right app: 
       * https://github.com/innocarpe/actions-slack
       * https://github.com/marketplace/actions/actions-slack
   * [x] Create a new app here: https://api.slack.com/apps/
   * [x] Give it a name: "Oxur Github Actions"
   * [x] Give it a description: "Slack status updates for Oxur Github Actions"
   * [x] Click "Add features and functionality" and select "Incoming Webhooks"
   * [x] When prompted, add it to #cicd Slack channel
   * [x] Copy the new webhook URL
   * [x] Go to "secrets" in oxur/component repo settings and create entry for `CICD_BOT_WEBHOOK` pasting the value copied above
   * [x] Copy secrets from Github Actions bot setup: https://api.slack.com/apps/ARTAUSN2X=
   * [x] Click "Add features and functionality" and select "Bots"
   * [x] Edit app display name: 
       * Display Name (Bot Name): "Github Actions Bot"
       * Default Name: githubcicd
   * [x] Check "Always Show My Bot as Online"
   * [x] Go to "OAuth & Permissions" and copy "Bot User OAuth Access Token"
   * [x] Go to "secrets" in oxur/component repo settings and create entry for `CICD_BOT_TOKEN` pasting the value copied above

**Comment by oubiwann** [comment]
```yaml
    - name: Notify CI/CD Slack Channel
      uses: innocarpe/actions-slack@v1
      with:
        status: ${{ job.status }}
        success_text: '✅ Build for ${{ github.repository }} succeeded! 😄🌈🐴🚢🐿 (commit id: ${{ github.sha }})'
        failure_text: '❌ Build for ${{ github.repository }} failed! 🤬💣🔥🚒 (commit id: ${{ github.sha }})'
        cancelled_text: '🚧 Build for ${{ github.repository }} was cancelled ... 😯🦡 (commit id: ${{ github.sha }})'
      env:
        GITHUB_TOKEN: ${{ secrets.CICD_BOT_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.CICD_BOT_WEBHOOK }}
      if: always()
```
